# Generated by Django 3.0.8 on 2022-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0003_remove_allpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='images',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
