# Generated by Django 3.0.8 on 2022-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0006_auto_20220117_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(default='3.jpg', upload_to='profile'),
        ),
    ]
