# Generated by Django 3.0.8 on 2022-01-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0007_auto_20220123_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='p_image',
            new_name='pimage',
        ),
    ]
